to_do_project/to_do/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("to_do_app.urls", namespace="to_do_app")),
    path('profile/', include("user_profile.urls", namespace="user_profile")),
    path('todo_lists/', include("todo_lists.urls", namespace="todo_lists")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_do_project/to_do_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "to_do_app"
urlpatterns = [
    path('', views.home, name='Home'),
    path('task/', views.task_list, name='task-list'),
    path('addtask/', views.add_task, name='add_task'),
    path('complete_task/<int:pk>/', views.complete_task, name='task_complete'),
    path('delete_task/<int:pk>', views.delete_task, name='delete_task'),
    path('about/', views.about, name='about'),
    path('faqs/', views.faqs, name='faqs'),
    path('features/', views.features, name='features'),
    path('update_task/<int:pk>/', views.edit_task, name='update_task'),
    path('register/', views.register_user, name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='to_do_app:Home'), name='logout'),
    path('email/', views.send_email, name='email'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html',
        success_url='/reset/done/'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'
    ), name='password_reset_complete'),


]

to_do_project/todo_lists/urls.py
from django.urls import path
from . import views



app_name = 'todo_lists'
urlpatterns = [
    path('complete_task_in_list/<int:pk>', views.complete_task_in_list, name='task_complete_in_list'),
    path('create_tasks_list/', views.create_list_of_tasks, name='create_tasks_list'),
    path('add_task_in_list/<int:pk>/', views.add_tasks_in_list, name='add_task_to_list'),
    path('menu_list_task/<int:pk>/', views.menu_list_task, name='menu_list_task'),
    path('update_list_task/<int:pk>/', views.update_task_from_list, name='update_list_task'),
    path('delete_list_task/<int:pk>/', views.delete_task_from_list, name='delete_task_from_list'),
    path('delete_list/<int:pk>', views.delete_list_of_task, name='delete_list'),
]

to_do_project/user_profile/urls.py
from django.urls import path
from .views import UserProfileDetailView, UserProfileUpdateView
from django.contrib.auth.decorators import login_required


app_name = "user_profile"
urlpatterns = [
    path('<int:pk>/', login_required(UserProfileDetailView.as_view()), name='profile_detail'),
    path('update/<int:pk>/', login_required(UserProfileUpdateView.as_view()), name='profile_edit')
]

to_do_project/to_do_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import EmailField
from todo_lists.models import ListOfTasks

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)


    def __str__(self):
        return self.name


class Tags(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name







class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)




class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    objects = CustomUserManager()


    def __str__(self):
        return self.first_name





class Task(models.Model):
    task_name = models.CharField(max_length=255)
    user = models.ForeignKey("CustomUser", on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    data_added = models.DateField(auto_now_add=True)
    due_date = models.DateTimeField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags, blank=True, related_name='tasks')
    list = models.ForeignKey(ListOfTasks, on_delete=models.CASCADE, related_name='tasks', null=True, blank=True)


    def __str__(self):
        return self.task_name

to_do_project/templates/todo/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    About us
</body>
</html>

to_do_project/templates/todo/add_task.html
{% extends 'todo/base.html' %}

{% block title %}Додати задачу{% endblock %}

{% block content %}
<div class="add_task_container">
  <h1 class="plus">Додати нове завдання</h1>
  <div class="forms_container">
    <form method="POST" class="task-form">
      {% csrf_token %}

      <!-- Назва завдання -->
      <div class="form-group">
        {{ form.task_name.label_tag }}
        {{ form.task_name }}
      </div>

      <!-- Опис -->
      <div class="form-group">
        {{ form.description.label_tag }}
        {{ form.description }}
      </div>

      <!-- Дата дедлайну -->
      <div class="form-group">
        {{ form.due_date.label_tag }}
        {{ form.due_date }}
      </div>

      <!-- Теги -->
      <div class="form-group">
        {{ form.tags.label_tag }}
        {{ form.tags }}
      </div>

      <!-- Кнопка збереження -->
      <div class="btn_add_task_container">
        <button type="submit" class="btn_add_task btn-primary">Зберегти завдання</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

to_do_project/templates/todo/add_task_in_list.html
{% extends 'todo/base.html' %}

{% block title %}Add New Task{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Add New Task to List: {{ tasklist.name }}</h1>

    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="mb-3">
            <label for="id_task_name" class="form-label">Task Name</label>
            {{ form.task_name.errors }}
            {{ form.task_name }}
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description.errors }}
            {{ form.description }}
        </div>


        <button type="submit" class="btn btn-primary">Add Task</button>
        <a href="{% url 'todo_lists:menu_list_task' tasklist.pk %}" class="btn btn-secondary ms-2">Cancel</a>
    </form>
</div>
{% endblock %}

to_do_project/templates/todo/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}To-Do App{% endblock %}</title>

    <!-- Bootstrap 5.3.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Твій власний CSS -->
    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}">
</head>
<body>
<div class="wrapper     flex-column min-vh-100">
    <!-- Bootstrap Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'to_do_app:Home' %}">To-Do App</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'to_do_app:Home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'to_do_app:features' %}">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'to_do_app:faqs' %}">FAQs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'to_do_app:about' %}">About</a>
                    </li>
                </ul>

                <div class="d-flex">
                    {% if user.is_authenticated %}
                        <span class="welcome_user">Вітаю, {{ user.first_name }}!</span>
                        {% if user_avatar %}
                                <img src="{{ user_avatar.url }}" alt="Avatar" class="user-avatar">
                        {% else %}
                            <img src="{% static 'todo/images/default-avatar.png' %}" alt="Default Avatar" class="user-avatar">
                        {% endif %}
                        <form action="{% url 'to_do_app:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-light me-2">Вийти</button>
                        </form>
                        <a href="{% url 'user_profile:profile_detail' user.userprofile.pk %}" class="btn btn-outline-light me-2">My account</a>
                    {% else %}

                        <a href="{% url 'to_do_app:login' %}" class="btn btn-outline-light me-2">Login</a>
                        <a href="{% url 'to_do_app:register' %}" class="btn btn-warning">Sign-up</a>

                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->

    <!-- Messages (errors, info, etc.) -->
    <div class="container mt-3">
        {% if messages %}
            <div>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <!-- Main content -->
    <main class="flex-fill">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="text-center py-4 bg-light mt-5">
        <p class="mb-0">© 2025 To-Do App | Django Project</p>
    </footer>
</div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

to_do_project/templates/todo/create_task_list.html
{% extends 'todo/base.html' %}

{% block title %}Add Task List{% endblock %}

{% block content %}
    <div class="add-task-list-form">
        <h1 class="text-center mb-4">Add New Task List</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create Task List</button>
        </form>
        <a href="{% url 'to_do_app:task-list' %}" class="btn btn-link">Back to Task List</a>
    </div>
{% endblock %}

to_do_project/templates/todo/faqs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      FAQs
</body>
</html>

to_do_project/templates/todo/features.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      Features
</body>
</html>

to_do_project/templates/todo/home_authenticated.html
{% extends 'todo/base.html' %}

{% block title %}Головна - To-Do App{% endblock %}


{% block content %}
<header class="header"><h1>Ласкаво просимо до To-Do App!</h1>
</header>
<div class="container_home">
    <h5>Натисни кнопку нижче, щоб переглянути список завдань:</h5>
    <a href="{% url 'to_do_app:task-list' %}">
        <button class="btn">Перейти до списку завдань</button>
    </a>
    <h5>Натисни кнопку нижче, щоб додати завдання:</h5>
    <a href="{% url 'to_do_app:add_task' %}">
        <button class="btn">Додати завдання</button>
    </a>
    <h5>Натисни кнопку нижче, щоб створити список завдань:</h5>
    <a href="{% url 'todo_lists:create_tasks_list' %}">
        <button class="btn">Створити список</button>
    </a>
</div>
{% endblock %}

to_do_project/templates/todo/home_unauthenticated.html
{% extends 'todo/base.html' %}

{% block title %}Головна - To-Do App{% endblock %}


{% block content %}
<header class="header"><h1>Ласкаво просимо до To-Do App!</h1></header>
<div class="centered_block">
<div class="unauth_container">
    <h2>Натисни кнопку нижче, щоб зарегеструватись:</h2>
    <a href="{% url 'to_do_app:register' %}">
        <button class="btn">Регестрація</button>
    </a>
    <h2>Натисни кнопку нижче, щоб залогінитися:</h2>
    <a href="{% url 'to_do_app:login' %}">
        <button class="btn">Увійти</button>
    </a>
</div>
</div>
{% endblock %}

to_do_project/templates/todo/login.html
{% extends 'todo/base.html' %}

{% block title %}Увійти{% endblock %}

{% block content %}
    <h1>Вхід до облікового запису</h1>
  <div class="container_login">
    <form method="post">
<div class="container_login_form">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-success">Увійти</button>
</div>
    </form>

    {% if form.errors %}
      <div class="alert alert-danger mt-3">
        <p>Невірне ім’я користувача або пароль.</p>
      </div>
    {% endif %}

    <p class="mt-3">
      Ще не маєш акаунта? <a href="{% url 'to_do_app:register' %}">Зареєструватися</a>
    </p>
    <p class="mt-4">
      Забули пароль? <a href="{% url 'to_do_app:password_reset' %}">Відновити пароль</a>
    </p>
  </div>
{% endblock %}

to_do_project/templates/todo/menu_task_list.html
{% extends 'todo/base.html' %}

{% block title %}Task List: {{ tasklist.name }}{% endblock %}

{% block content %}
<div class="container task-list-detail">
    <h1 class="text-center mb-4">Task List: {{ tasklist.name }}</h1>

    <div class="task-actions mb-3">
        <a href="{% url 'todo_lists:add_task_to_list' tasklist.pk %}  " class="btn btn-primary btn-sm me-2">Add New Task</a>
        <a href="{% url 'todo_lists:delete_list' tasklist.pk %}" class="btn btn-danger btn-sm me-2">Delete List</a>
        <a href="{% url 'to_do_app:task-list'%}" class="btn btn-danger btn-sm me-2">Back to Task Page</a>
        <a href="{% url 'to_do_app:Home' %}" class="btn btn-outline-secondary btn-sm">Home</a>
    </div>

    {% if tasks %}
        <h3>Tasks in this List:</h3>
        {% for task in tasks %}
            <article class="task-item d-flex justify-content-between align-items-start mb-3 p-3 border rounded">
                <div>
                    <h4 class="task-title mb-1">{{ task.task_name }}</h4>
                    <p class="task-description mb-1">{{ task.description }}</p>

                    {% if task.tags.exists %}
                    <p class="task-tags mb-1">
                        <strong>Tags:</strong>
                        {% for tag in task.tags.all %}
                            <span class="badge bg-secondary me-1">{{ tag.name }}</span>
                        {% endfor %}
                    </p>
                    {% endif %}

                    {% if task.due_date %}
                        <small class="text-muted">Due: {{ task.due_date|date:"d M Y, H:i" }}</small>
                    {% endif %}

                    {% if task.complete %}
                        <div class="mt-2">
                            <span class="badge bg-success">Completed</span>
                            <a href="{% url 'todo_lists:task_complete_in_list' task.pk %}" class="btn btn-sm btn-outline-info ms-2">Mark as Uncompleted</a>
                        </div>
                    {% else %}
                        <div class="mt-2">
                            <a href="{% url 'todo_lists:task_complete_in_list' task.pk %}" class="btn btn-sm btn-success">Mark as Completed</a>
                        </div>
                    {% endif %}
                </div>
                <div class="task-actions d-flex flex-column gap-2">
                    <a href="{% url 'todo_lists:update_list_task' task.pk %}" class="btn btn-outline-warning btn-sm">Update Task</a>
                    <a href="{% url 'todo_lists:delete_task_from_list' task.pk %}" class="btn btn-outline-danger btn-sm">Delete Task</a>
                </div>
            </article>
        {% endfor %}
    {% else %}
        <p>No tasks in this list yet.</p>
    {% endif %}
</div>
{% endblock %}

to_do_project/templates/todo/register.html
{% extends 'todo/base.html' %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
<h1>Реєстрація користувача</h1>
  <div class="container_register">

    <form method="post">
      <div class="container_register_form">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-primary">Зареєструватися</button>
      </div>
    </form>

    <p class="mt-3">Вже є акаунт? <a href="{% url 'to_do_app:login' %}">Увійти</a></p>
  </div>
{% endblock %}

to_do_project/templates/todo/task_list.html
{% extends 'todo/base.html' %}

{% block title %}To-Do Tasks & Lists{% endblock %}

{% block content %}
    <h1 class="text-center mb-4">To-Do List</h1>
<div class="container task-list">

    <aside class="task-sidebar mb-3">
        <a href="{% url 'to_do_app:add_task' %}" class="btn btn-primary btn-sm me-2">Add New Task</a>
        <a href="{% url 'todo_lists:create_tasks_list' %}" class="btn btn-success btn-sm me-2">Add New List</a>
        <a href="{% url 'to_do_app:Home' %}" class="btn btn-outline-danger btn-sm">Home page</a>
        <form method="get" action="{% url 'to_do_app:task-list' %}">
            <label for="filters">Фільтр:</label>
            <select name="filters" id="filters" onchange="this.form.submit()">
                <option value="">-- Усі --</option>
                <option value="done" {% if request.GET.filters == 'done' %}selected{% endif %}>Лише виконані</option>
                <option value="undone" {% if request.GET.filters == 'undone' %}selected{% endif %}>Лише невиконані</option>
                <option value="tags" {% if request.GET.filters == 'tags' %}selected{% endif %}>За тегом</option>
            </select>

            {% if request.GET.filters == 'tags' %}
                <label for="tag">Оберіть тег:</label>
                <select name="tag" id="tag" onchange="this.form.submit()">
                    {% for tag in all_tags %}
                        <option value="{{ tag.name }}" {% if request.GET.tag == tag.name %}selected{% endif %}>
                            {{ tag.name }}
                        </option>
                    {% endfor %}
                </select>
            {% endif %}
        </form>

            <!-- зберігаємо значення поточного сортування -->
            <input type="hidden" name="sort" value="{{ request.GET.sort }}">
        </form>
<!--        Categories-->
        <h3 class="task-list-text">Task Lists: </h3>
        {% if tasklists %}
        <ul class="list-group">
            {% for tasklist in tasklists %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'todo_lists:menu_list_task' tasklist.pk %}">
                    {{ tasklist.name }}
                </a>
                <div class="badge-container">
                    <p>Done:</p>
                        <span class="badge bg-success me-2">
                            {{ tasklist.success_percentage }}%
                        </span>
                    <span class="badge bg-primary rounded-pill">
                            {{ tasklist.tasks.count }}
                        </span>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No lists available.</p>
        {% endif %}
    </aside>

<div class="main_flex_container">
    <div class="search_container">

        <!--        SEARCH -->
    <form method="GET" action="{% url 'to_do_app:task-list' %}" class="search_form" >

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">пошук</button>
        <input type="hidden" name="sort" value="{{ request.GET.sort }}">
        <input type="hidden" name="filters" value="{{ request.GET.filters }}">
    </form>
     <!--        Sorting -->
        <form method="get" action="{% url 'to_do_app:task-list' %}">
            <label for="sort">Сортувати:</label>
            <select name="sort" id="sort" onchange="this.form.submit()">
                <option value="">-- Не сортувати --</option>
                <option value="done" {% if request.GET.sort == 'done' %}selected{% endif %}>Виконані вгорі</option>
                <option value="undone" {% if request.GET.sort == 'undone' %}selected{% endif %}>Невиконані вгорі</option>
                <option value="data_added" {% if request.GET.sort == 'data_added' %}selected{% endif %}>За датою</option>
                <option value="alphabet" {% if request.GET.sort == 'alphabet' %}selected{% endif %}>За алфавітом</option>
            </select>

            <!-- зберігаємо значення поточного фільтра -->
            <input type="hidden" name="filters" value="{{ request.GET.filters }}">
        </form>
    </div>



    <h3 class="mt-4">Tasks: </h3>
    {% if tasks %}
        {% for task in tasks %}
            <article class="task-item d-flex justify-content-between align-items-start mb-3 p-3 border rounded">
                <div>
                    <h4 class="task-title mb-1">{{ task.task_name }}</h4>
                    <p class="task-description mb-1">{{ task.description }}</p>
                    <p class="task-description mb-1">{{ task.data_added }}</p>

                    {% if task.tags.exists %}
                    <p class="task-tags mb-1">
                        <strong>Tags:</strong>
                        {% for tag in task.tags.all %}
                            <span class="badge bg-secondary me-1">{{ tag.name }}</span>
                        {% endfor %}
                    </p>
                    {% endif %}

                    {% if task.due_date %}
                        <small class="text-muted">Due: {{ task.due_date|date:"d M Y, H:i" }}</small>
                    {% endif %}

                    {% if task.complete %}
                        <div class="mt-2">
                            <a href="{% url 'to_do_app:task_complete' task.pk %}" class="btn btn-sm btn-outline-info ms-2">Mark as Uncompleted</a>
                            <span class="badge bg-success">Completed</span>
                        </div>
                    {% else %}
                        <div class="mt-2">
                            <a href="{% url 'to_do_app:task_complete' task.pk %}" class="btn btn-sm btn-success">Mark as Completed</a>
                        </div>
                    {% endif %}
                </div>
                <div class="task-actions-tasks">
                    <a href="{% url 'to_do_app:update_task' task.pk %}" class="btn btn-outline-warning btn-sm">Update task</a>
                    <a href="{% url 'to_do_app:delete_task' task.pk %}" class="btn btn-outline-danger btn-sm">Delete task</a>
                </div>
            </article>
        {% endfor %}
    {% else %}
        <p>No tasks without a list.</p>
    {% endif %}

{% endblock %}
</div>
</div>

to_do_project/templates/todo/update_task.html
{% extends 'todo/base.html' %}


{% block title %}Update Task{% endblock %}


{% block content %}
    <div class="add-task-form">
        <h1 class="text-center mb-4" >Update Task</h1>
        <form method="post">
            {% csrf_token %}
             {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save Task</button>
        </form>
        <a href="{% url 'to_do_app:task-list' %}" class="btn btn-link">Back to Task List</a>
    </div>
{% endblock %}